CREATE TABLE IF NOT EXISTS temp_voice_config (
    guild_id VARCHAR(255) PRIMARY KEY,
    category_id VARCHAR(255) NOT NULL,
    trigger_channel_id VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS temp_voice_channels (
    guild_id VARCHAR(255) NOT NULL,
    user_id VARCHAR(255) NOT NULL,
    channel_id VARCHAR(255) PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
