CREATE TABLE IF NOT EXISTS music_config (
    guild_id VARCHAR(255) PRIMARY KEY,
    music_channel_id VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
