CREATE TABLE IF NOT EXISTS autorole_config (
    guild_id VARCHAR(255) PRIMARY KEY,
    role_id VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);