CREATE TABLE IF NOT EXISTS facts (
    id SERIAL PRIMARY KEY,
    guild_id VARCHAR(255) NOT NULL,
    text TEXT NOT NULL,
    author_id VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
