CREATE TABLE IF NOT EXISTS nickname_config (
    guild_id VARCHAR(255) PRIMARY KEY REFERENCES guilds(id) ON DELETE CASCADE,
    template VARCHAR(255) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
